### ISSUE TITLE
Error: /Login/token/staff can obtain token, but invalid for other API call.

### ISSUE THREAD

**Issue by cetsupport** [DigitalState/Platform#15]
# Symptom Description:

I following the instruction installed lab environment on top of windows 10.

The key was generated from putty, the public key was directly saved from putty. The private key was export to OPENSSH key format as looks like Authentication service doesn't accept pkcs#12 format.

## Issue 1
First the docker-compose handing on **Attaching to sdk**
```
PS C:\dev\sdk> docker-compose up
Building sdk
Step 1/5 : FROM williamyeh/ansible:alpine3
alpine3: Pulling from williamyeh/ansible
1160f4abea84: Pull complete
f39516e0568c: Pull complete
Digest: sha256:7b8d95ddca0736bfc6e81955aee04c5b8ff9597e8c68151b0893a84c6ec70b17
Status: Downloaded newer image for williamyeh/ansible:alpine3
 ---> 995ede431897
Step 2/5 : RUN mkdir -p /root/.ssh
 ---> Running in d57d28408250
 ---> 56eafb8050a6
Removing intermediate container d57d28408250
Step 3/5 : COPY sdk/ssh /root/.ssh
 ---> cd7a04d25bdf
Step 4/5 : RUN chmod -R 600 /root/.ssh
 ---> Running in 9999bf75f2e1
 ---> 25d5216a493a
Removing intermediate container 9999bf75f2e1
Step 5/5 : WORKDIR /etc/ansible/env/lab
 ---> 913f7c449017
Removing intermediate container 3cbd4889178a
Successfully built 913f7c449017
Successfully tagged sdk_sdk:latest
WARNING: Image for service sdk was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating sdk ...
Creating sdk ... done
Attaching to sdk
```
I login to sdk container, checked all volumes been correctly mounted. So I leave it and continue deploy the lab environment.

Tried restart docker daemon and windows, no helps.

## Issue 2
The deployment successfully done. Then I try to access those API by following the instruction.

First API call is Login/tokens/staff. I can get the token and I checked in the postman the token variable was updated to returned token by Login/tokens/staff api call.

Second API call I try to access User/users, then I got error 401.

```
{
    "code": 401,
    "message": "Invalid JWT Token"
}
```

# Quesion:
Any suggestion how to fix issue 2? Possible issue 2 caused by issue 1?

**Comment by marioprudhomme** [comment]
For issue 2:

Seems like the authentication microservice is unable to validate the token. Perhaps the issue is related to the keys.

I have posted a sample private/public key pair [here](https://gist.github.com/mario-digitalstate/44b1d6209697d571eb775a8df042aa38) (the passphrase is 1111) for you to test to rule out if the issue is related to putty keys. 

Either copy/paste the key files manually in each applicable microservices (C:\dev\sdk\app\\*\var\jwt\) or copy the the key files in  C:\dev\sdk\resource\jwt\lab\ and re-run the ansible playbook. 
```
cd /etc/ansible/env/lab
ansible-playbook jwt/download.yml
```

You will also need to change the passphrase config in each microservice (C:\dev\sdk\app\\*\app\config\parameters.yml#jwt_key_pass_phrase: ) or update your lab inventory file passphrase and rerun the ansible playbook.
```
ansible-playbook jwt/configure.yml
```

While on windows, I actually use the sdk docker container to generate keys (instead of putty) by running the following commands:

```
cd /srv/authentication/var/jwt
openssl genrsa -out key -aes256 4096
openssl rsa -pubout -in key -out key.pub
```

In the example above, I `cd` to a folder that's already shared with my host computer. After running the command, you see the key files appearing in windows explorer at C:\dev\sdk\app\authentication\var\jwt, from their I simply cut/paste them to the C:\dev\sdk\resource\jwt\lab folder.

**Comment by cetsupport** [comment]
Thanks @mario-digitalstate . The problem was fixed by your suggestion.

I verified that gained token validated by other service.

Issue closed.

**Comment by akamanocha** [comment]
Hey @marioprudhomme I am having the same issue, 401 Unauthorised and Invalid JWT key.

Can you please share the keys (kinda urgently) 

Or let me know anything else to change besides jwt_key_pass_phrase. encryption.secret needs to be changed too (someone mentioned that)?
